### ISSUE TITLE
Packet opcode 231 - Swapping items into invalid slots

### ISSUE THREAD

**Issue by cryptospout** [Hadyn/mopar#4]
You can swap items into invalid bag slots such as -1 this causes the character file to not load correctly when entering the world. I need the account silabsoft reset.

**Comment by cryptospout** [comment]
This one is actually more serious, although when putting the item into a negative slot you kill your account you can also move items into non existing slots lets say (slot 45) and the item is retained upon re logging.

**Comment by Hadyn** [comment]
Fixed as of 8/8/15
